version: "3.9"
services:

  frontend:
    container_name: crypto-frontend
    build: ./frontend/
    ports:
      - 80:80
      - 443:443
    networks:
      - crypto

  # postgres:
  #   container_name: postgres
  #   image: postgres:13-alpine
  #   environment:
  #     - POSTGRES_USER=admin
  #     - POSTGRES_PASSWORD=secret
  #     - POSTGRES_DB=cryptoplatform
  #   ports:
  #     - 5432:5432
  #   networks:
  #     - crypto
  #   volumes:
  #     - postgres-db:/var/lib/postgresql/data

  # pgadmin:
  #   container_name: pgadmin
  #   image: dpage/pgadmin4:5.2
  #   environment:
  #     - PGADMIN_DEFAULT_EMAIL=admin@admin.ch
  #     - PGADMIN_DEFAULT_PASSWORD=secret
  #   ports:
  #     - 5050:80
  #   networks:
  #     - crypto
  #   volumes:
  #     - pgadmin-data:/root/.pgadmin
  #   depends_on:
  #     - postgres

  # redis:
  #   container_name: redis
  #   image: redis:6-alpine
  #   ports:
  #     - 6379:6379
  #   networks:
  #     - crypto
  #   volumes:
  #     - redis-data:/data


networks:
  crypto:
    driver: bridge

# volumes:
#   postgres-db:
#   pgadmin-data:
#   redis-data:
        
